export default {
  handle: null,
  charRole: null,
  age: null,
  charPoints: null,
  availCharPoints: null,
  stats: {
    int: { name: 'Intelligence', nameValue: 'int', points: 5 },
    cool: { name: 'Cool', nameValue: 'cool', points: 0 },
    // int:5,
    // ref: { 0: null, 1: null },
    // tech: null,
    // cool: null,
    // attr: null,
    // luck: null,
    // ma: null,
    // body: null,
    // emp: { 0: null, 1: null },
    // run: null,
    // leap: null,
    // carry: null,
    // lift: null,
  },
};
