export default {
  handle: null,
  role: null,
  age: null,
  charPoints: null,
  stats: {
    int: null,
    ref: { 0: null, 1: null },
    tech: null,
    cool: null,
    attr: null,
    luck: null,
    ma: null,
    body: null,
    emp: { 0: null, 1: null },
    run: null,
    leap: null,
    carry: null,
    lift: null,
  },
};
