export default {
  solo: {
    name: 'Solo',
    careerSkills: [
      'Combat Sense',
      'Awareness/Notice',
      'Handgun',
      'Brawling',
      'Martial Art 1',
      'Martial Art 2',
      'Martial Art 3',
      'Melee',
      'Weaponsmith',
      'Rifle',
      'Athletics',
      'Submachinegun',
      'Stealth',
    ],
  },
  rocker: {
    name: 'Rockerboy',
    careerSkills: [
      'Charismatic Leadership',
      'Awareness/Notice',
      'Perform',
      'Wardrobe & Style',
      'Composition',
      'Brawling',
      'Play Instrument',
      'Streetwise',
      'Persuasion & Fast Talk',
      'Seduction',
    ],
  },
  netrunner: {
    name: 'Netrunner',
    careerSkills: [
      'Interface',
      'Awareness/Notice',
      'Basic Tech',
      'Education & General Knowledge',
      'System Knowledge',
      'CyberTech',
      'Cyberdeck Design',
      'Composition',
      'Electronics',
      'Programming',
    ],
  },
  media: {
    name: 'Media',
    careerSkills: [
      'Credibility',
      'Awareness/Notice',
      'Composition',
      'Education & General Knowledge',
      'Persuasion & Fast Talk',
      'Human Perception',
      'Social',
      'Streetwise',
      'Photo & Film',
      'Interview',
    ],
  },
  nomad: {
    name: 'Nomad',
    careerSkills: [
      'Family',
      'Awareness/Notice',
      'Endurance',
      'Melee',
      'Driving',
      'Basic Tech',
      'Wilderness Survival',
      'Brawling',
      'Athletics',
    ],
  },
  fixer: {
    name: 'Fixer',
    careerSkills: [
      'Streetdeal',
      'Awareness/Notice',
      'Forgery',
      'Handgun',
      'Brawling',
      'Melee',
      'Pick Lock',
      'Pick Pocket',
      'Intimidate',
      'Persuasion & Fast Talk',
    ],
  },
  cop: {
    name: 'Cop',
    careerSkills: [
      'Authority',
      'Awareness/Notice',
      'Handgun',
      'Human Perception',
      'Athletics',
      'Education & General Knowledge',
      'Brawling',
      'Melee',
      'Interrogation',
      'Streetwise',
    ],
  },
  corp: {
    name: 'Corp',
    careerSkills: [
      'Resources',
      'Awareness/Notice',
      'Human Perception',
      'Education & General Knowledge',
      'Library Search',
      'Social',
      'Persuasion & Fast Talk',
      'Stock Market',
      'Wardrobe & Style',
      'Personal Grooming',
    ],
  },
  techie: {
    name: 'Techie',
    careerSkills: [
      'Jury Rig',
      'Awareness/Notice',
      'Human Perception',
      'Education & General Knowledge',
      'Library Search',
      'Social',
      'Persuasion & Fast Talk',
      'Stock Market',
      'Wardrobe & Style',
      'Personal Grooming',
    ],
  },
  medtechie: {
    name: 'Medtechie',
    careerSkills: [
      'Medical Tech',
      'Awareness/Notice',
      'Basic Tech',
      'Diagnose Illness',
      'Education & General Knowledge',
      'Cryotank Operation',
      'Library Search',
      'Pharmaceuticals',
      'Zoology',
      'Human Perception',
    ],
  },
};
