export default {
  masterSkillList: [
    { name: 'Authority', points: 0 },
    { name: 'Charismatic Leadership', points: 0 },
    { name: 'Combat Sense', points: 0 },
    { name: 'Credibility', points: 0 },
    { name: 'Family', points: 0 },
    { name: 'Interface', points: 0 },
    { name: 'Authority', points: 0 },
    { name: 'Jury Rig', points: 0 },
    { name: 'Medical Tech', points: 0 },
    { name: 'Resources', points: 0 },
    { name: 'Streetdeal', points: 0 },
    { name: 'Archery', points: 0 },
    { name: 'Athletics', points: 0 },
    { name: 'Brawling', points: 0 },
    { name: 'Dance', points: 0 },
    { name: 'Dodge & Escape', points: 0 },
    { name: 'Driving', points: 0 },
    { name: 'Fencing', points: 0 },
    { name: 'Handgun', points: 0 },
    { name: 'Heavy Weapons', points: 0 },
    { name: 'Martial Art 1', points: 0 },
    { name: 'Martial Art 2', points: 0 },
    { name: 'Martial Art 3', points: 0 },
    { name: 'Melee', points: 0 },
    { name: 'Motorcycle', points: 0 },
    { name: 'Operate Heavy Machinery', points: 0 },
    { name: 'Pilot', points: 0 },
    { name: 'Pilot (Gyro)', points: 0 },
    { name: 'Pilot (Fixed Wing)', points: 0 },
    { name: 'Pilot (Dirigible)', points: 0 },
    { name: 'Pilot (Vect. Thrust Vehicle)', points: 0 },
    { name: 'Rifle', points: 0 },
    { name: 'Stealth', points: 0 },
    { name: 'Submachinegun', points: 0 },
    { name: 'Aero Tech', points: 0 },
    { name: 'AV Tech', points: 0 },
    { name: 'Basic Tech', points: 0 },
    { name: 'Cryotank Operation', points: 0 },
    { name: 'Cyberdeck Design', points: 0 },
    { name: 'CyberTech', points: 0 },
    { name: 'Demolitions', points: 0 },
    { name: 'Disguise', points: 0 },
    { name: 'Electronics', points: 0 },
    { name: 'Electronic Security', points: 0 },
    { name: 'First Aid', points: 0 },
    { name: 'Forgery', points: 0 },
    { name: 'Gyro Tech', points: 0 },
    { name: 'Paint or Draw', points: 0 },
    { name: 'Photo & Film', points: 0 },
    { name: 'Pharmaceuticals', points: 0 },
    { name: 'Pick Lock', points: 0 },
    { name: 'Pick Pocket', points: 0 },
    { name: 'Play Instrument', points: 0 },
    { name: 'Weaponsmith', points: 0 },
    { name: 'Interrogation', points: 0 },
    { name: 'Intimidate', points: 0 },
    { name: 'Oratory Sense', points: 0 },
    { name: 'Resist Torture/Drugs', points: 0 },
    { name: 'Streetwise', points: 0 },
    { name: 'Human Perception', points: 0 },
    { name: 'Interview', points: 0 },
    { name: 'Leadership', points: 0 },
    { name: 'Seduction', points: 0 },
    { name: 'Social', points: 0 },
    { name: 'Persuasion & Fast Talk', points: 0 },
    { name: 'Perform', points: 0 },
    { name: 'Accounting', points: 0 },
    { name: 'Anthropology', points: 0 },
    { name: 'Awareness/Notice', points: 0 },
    { name: 'Biology', points: 0 },
    { name: 'Botany', points: 0 },
    { name: 'Chemistry', points: 0 },
    { name: 'Composition', points: 0 },
    { name: 'Diagnose Illness', points: 0 },
    { name: 'Education & General Knowledge', points: 0 },
    { name: 'Expert', points: 0 },
    { name: 'Gamble', points: 0 },
    { name: 'Geology', points: 0 },
    { name: 'Hide/Evade', points: 0 },
    { name: 'History', points: 0 },
    { name: 'Languages', points: 0 },
    { name: 'Library Search', points: 0 },
    { name: 'Mathematics', points: 0 },
    { name: 'Physics', points: 0 },
    { name: 'Programming', points: 0 },
    { name: 'Shadow/Track', points: 0 },
    { name: 'Stock Market', points: 0 },
    { name: 'System Knowledge', points: 0 },
    { name: 'Teaching', points: 0 },
    { name: 'Wilderness Survival', points: 0 },
    { name: 'Zoology', points: 0 },
    { name: 'Personal Grooming', points: 0 },
    { name: 'Wardrobe & Style', points: 0 },
    { name: 'Endurance', points: 0 },
    { name: 'Strength Feat', points: 0 },
    { name: 'Swimming', points: 0 },
  ],
};
